### ISSUE TITLE
beefly与tensorflow版本问题

### ISSUE THREAD

**Issue by niecongchong** [Hourout/beefly#1]
请问作者，我install beefly时，同时安装了CPU版本的tensorflow，此时程序正常运行，但是若是我卸掉CPU版的tensorflow，他此时运行就会报错：
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-180b24602742> in <module>()
      7 from keras.optimizers import SGD
      8 from keras.callbacks import ReduceLROnPlateau
----> 9 import beefly

~\Anaconda3\lib\site-packages\beefly\__init__.py in <module>()
----> 1 from tensorview.train import PlotMetrics
      2 from tensorview.train import PlotMetricsOnBatch
      3 from tensorview.train import PlotMetricsOnEpoch
      4 from tensorview.train import __beefly_version__
      5 import warnings

~\AppData\Roaming\Python\Python36\site-packages\tensorview\__init__.py in <module>()
----> 1 from tensorview import train
      2 from tensorview import model
      3 
      4 __version__ = '0.2.0'
      5 __author__ = 'JinQing Lee'

~\AppData\Roaming\Python\Python36\site-packages\tensorview\train\__init__.py in <module>()
----> 1 from tensorview.train._general_plot import *
      2 from tensorview.train._keras_callbacks_PlotMetricsOnBatch import *
      3 from tensorview.train._keras_callbacks_PlotMetricsOnEpoch import *
      4 
      5 __beefly_version__ = '0.8.0'

~\AppData\Roaming\Python\Python36\site-packages\tensorview\train\_general_plot.py in <module>()
      1 from collections import defaultdict
      2 
----> 3 from tensorflow.io.gfile import exists
      4 import matplotlib.pyplot as plt
      5 from IPython.display import clear_output

ModuleNotFoundError: No module named 'tensorflow.io'

**Comment by Hourout** [comment]
sorry，beefly 安装需要依赖tensorflow2.0.0，同时我们建议使用tensorview，beefly之后只维护bug不增加新特性，新功能全部迁移至tensorview。
